import { db } from '@/db';
import { notifications } from '@/db/schema';

async function main() {
    const sampleNotifications = [
        {
            userId: 1,
            title: 'Booking Confirmed',
            message: 'Your booking at Luxury Beach Villa has been confirmed for March 15-20, 2024.',
            type: 'booking',
            isRead: false,
            relatedId: 1,
            createdAt: new Date('2024-03-01T10:30:00Z').toISOString(),
        },
        {
            userId: 2,
            title: 'New Message',
            message: 'Sarah Johnson sent you a message about your property in Miami Beach.',
            type: 'message',
            isRead: true,
            relatedId: 5,
            createdAt: new Date('2024-03-02T14:20:00Z').toISOString(),
        },
        {
            userId: 3,
            title: 'New Review Received',
            message: 'Michael Chen left a 5-star review for your Mountain Retreat property.',
            type: 'review',
            isRead: false,
            relatedId: 8,
            createdAt: new Date('2024-03-03T09:15:00Z').toISOString(),
        },
        {
            userId: 4,
            title: 'Payment Received',
            message: 'You have received payment of $1,250 for booking #1234. Funds will be available in 3-5 business days.',
            type: 'payment',
            isRead: true,
            relatedId: 15,
            createdAt: new Date('2024-03-04T16:45:00Z').toISOString(),
        },
        {
            userId: 5,
            title: 'System Update',
            message: 'We have updated our terms of service and privacy policy. Please review the changes.',
            type: 'system',
            isRead: false,
            relatedId: null,
            createdAt: new Date('2024-03-05T08:00:00Z').toISOString(),
        },
        {
            userId: 6,
            title: 'Booking Request',
            message: 'Emma Wilson has requested to book your Downtown Loft from April 1-5, 2024.',
            type: 'booking',
            isRead: true,
            relatedId: 22,
            createdAt: new Date('2024-03-06T11:30:00Z').toISOString(),
        },
        {
            userId: 7,
            title: 'New Message',
            message: 'Host David Martinez replied to your inquiry about pet-friendly accommodations.',
            type: 'message',
            isRead: false,
            relatedId: 12,
            createdAt: new Date('2024-03-07T13:25:00Z').toISOString(),
        },
        {
            userId: 8,
            title: 'Review Reminder',
            message: 'Please leave a review for your recent stay at Oceanview Paradise. Your feedback helps other guests.',
            type: 'review',
            isRead: true,
            relatedId: 6,
            createdAt: new Date('2024-03-08T10:00:00Z').toISOString(),
        },
        {
            userId: 9,
            title: 'Payment Pending',
            message: 'Your payout of $2,800 is being processed and will arrive within 2 business days.',
            type: 'payment',
            isRead: false,
            relatedId: 28,
            createdAt: new Date('2024-03-09T15:40:00Z').toISOString(),
        },
        {
            userId: 10,
            title: 'Booking Cancelled',
            message: 'Guest James Anderson has cancelled their booking for June 10-15. Full refund has been processed.',
            type: 'booking',
            isRead: true,
            relatedId: 35,
            createdAt: new Date('2024-03-10T09:20:00Z').toISOString(),
        },
        {
            userId: 11,
            title: 'New Message',
            message: 'You have 3 unread messages from potential guests asking about your property amenities.',
            type: 'message',
            isRead: false,
            relatedId: 18,
            createdAt: new Date('2024-03-11T12:15:00Z').toISOString(),
        },
        {
            userId: 12,
            title: 'Review Posted',
            message: 'Your review for Cozy Mountain Cabin has been published and is now visible to other users.',
            type: 'review',
            isRead: true,
            relatedId: 9,
            createdAt: new Date('2024-03-12T14:30:00Z').toISOString(),
        },
        {
            userId: 13,
            title: 'Payment Failed',
            message: 'Your payment for booking #4567 could not be processed. Please update your payment method.',
            type: 'payment',
            isRead: false,
            relatedId: 42,
            createdAt: new Date('2024-03-13T10:50:00Z').toISOString(),
        },
        {
            userId: 14,
            title: 'Security Alert',
            message: 'We detected a new login to your account from a different device. If this was not you, please secure your account immediately.',
            type: 'system',
            isRead: true,
            relatedId: null,
            createdAt: new Date('2024-03-14T16:20:00Z').toISOString(),
        },
        {
            userId: 15,
            title: 'Booking Upcoming',
            message: 'Your stay at Seaside Villa starts in 3 days. Check-in time is 3:00 PM on March 18, 2024.',
            type: 'booking',
            isRead: false,
            relatedId: 11,
            createdAt: new Date('2024-03-15T08:45:00Z').toISOString(),
        },
        {
            userId: 1,
            title: 'New Message',
            message: 'Host Rachel Green sent you check-in instructions and parking information for your upcoming stay.',
            type: 'message',
            isRead: true,
            relatedId: 25,
            createdAt: new Date('2024-03-16T11:00:00Z').toISOString(),
        },
        {
            userId: 3,
            title: 'Payment Successful',
            message: 'Your payment of $980 for City Center Apartment has been successfully processed.',
            type: 'payment',
            isRead: false,
            relatedId: 19,
            createdAt: new Date('2024-03-17T13:35:00Z').toISOString(),
        },
        {
            userId: 5,
            title: 'Review Response',
            message: 'Host Christopher Lee has responded to your review of their property.',
            type: 'review',
            isRead: true,
            relatedId: 14,
            createdAt: new Date('2024-03-18T09:40:00Z').toISOString(),
        },
        {
            userId: 8,
            title: 'Booking Modified',
            message: 'Your booking dates have been updated to May 5-10, 2024 as per your request.',
            type: 'booking',
            isRead: false,
            relatedId: 31,
            createdAt: new Date('2024-03-19T15:10:00Z').toISOString(),
        },
        {
            userId: 12,
            title: 'Special Offer',
            message: 'You have received a 15% discount code for your next booking. Use code SPRING2024 at checkout.',
            type: 'system',
            isRead: true,
            relatedId: null,
            createdAt: new Date('2024-03-20T10:25:00Z').toISOString(),
        },
    ];

    await db.insert(notifications).values(sampleNotifications);
    
    console.log('✅ Notifications seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});