import { db } from '@/db';
import { reviews } from '@/db/schema';

async function main() {
    const sampleReviews = [
        {
            propertyId: 1,
            userId: 1,
            rating: 4.8,
            comment: 'Absolutely loved our stay at this beautiful beachfront property! The location was perfect, just steps from the ocean. The host was incredibly responsive and provided great local recommendations. The place was spotlessly clean and had everything we needed for a comfortable vacation. Would definitely book again!',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2024-03-15').toISOString(),
        },
        {
            propertyId: 2,
            userId: 3,
            rating: 4.6,
            comment: 'Great apartment in the heart of the city with stunning skyline views. The modern amenities were top-notch and the building facilities were excellent. Only minor issue was some street noise at night, but the comfortable beds made up for it. Perfect location for exploring downtown and all the major attractions.',
            cleanliness: 5,
            accuracy: 4,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2024-04-02').toISOString(),
        },
        {
            propertyId: 3,
            userId: 5,
            rating: 4.9,
            comment: 'This mountain retreat exceeded all our expectations! The cabin was cozy and beautifully decorated with rustic charm. We spent our evenings by the fireplace enjoying the peaceful surroundings. The hiking trails nearby were fantastic, and the host provided excellent maps and suggestions. A truly memorable getaway from city life.',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 5,
            createdAt: new Date('2024-05-18').toISOString(),
        },
        {
            propertyId: 1,
            userId: 7,
            rating: 4.7,
            comment: 'Wonderful beach house with amazing ocean views from every room. The outdoor deck was perfect for morning coffee and evening sunsets. Kitchen was well-equipped for cooking family meals. Beach access was easy and convenient. Host was very accommodating with our check-in time. Great value for a beachfront property.',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 4,
            communication: 5,
            location: 5,
            value: 5,
            createdAt: new Date('2024-06-22').toISOString(),
        },
        {
            propertyId: 4,
            userId: 2,
            rating: 4.5,
            comment: 'Lovely country cottage perfect for a peaceful weekend retreat. The garden was beautiful and well-maintained. Inside was charming with lots of character and comfortable furnishings. Great local pub within walking distance. WiFi was reliable for remote work. Would recommend for anyone looking to escape the city hustle.',
            cleanliness: 4,
            accuracy: 5,
            checkIn: 5,
            communication: 4,
            location: 4,
            value: 5,
            createdAt: new Date('2024-07-10').toISOString(),
        },
        {
            propertyId: 5,
            userId: 9,
            rating: 4.8,
            comment: 'Fantastic lakefront cabin with breathtaking views! The private dock was perfect for kayaking and fishing. Evenings on the porch watching the sunset were unforgettable. Inside was clean and comfortable with a fully stocked kitchen. Host provided great recommendations for local restaurants and activities. We will definitely return!',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2024-08-05').toISOString(),
        },
        {
            propertyId: 6,
            userId: 11,
            rating: 4.6,
            comment: 'Beautiful villa with a stunning pool area that our kids absolutely loved. The outdoor kitchen was perfect for BBQs and family gatherings. Spacious bedrooms with comfortable beds ensured everyone had a great sleep. Location was quiet yet close to shops and restaurants. Host was helpful and check-in was seamless.',
            cleanliness: 5,
            accuracy: 4,
            checkIn: 5,
            communication: 5,
            location: 4,
            value: 5,
            createdAt: new Date('2024-09-14').toISOString(),
        },
        {
            propertyId: 2,
            userId: 4,
            rating: 4.7,
            comment: 'Perfect urban apartment for our business trip. Walking distance to conference center and excellent restaurants. The workspace was well-designed with good lighting and comfortable chair. Building amenities including gym and business center were valuable. Host communication was professional and prompt. Would definitely stay again for work trips.',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2024-10-01').toISOString(),
        },
        {
            propertyId: 3,
            userId: 6,
            rating: 4.9,
            comment: 'Incredible mountain cabin that felt like a home away from home! The views from the deck were spectacular every morning. We enjoyed hiking the nearby trails and relaxing in the hot tub after long days exploring. Kitchen had everything we needed for cooking. Host was super friendly and gave us great local tips. Highly recommend!',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 5,
            createdAt: new Date('2024-10-20').toISOString(),
        },
        {
            propertyId: 1,
            userId: 8,
            rating: 4.8,
            comment: 'Amazing beachfront property perfect for our family reunion! Everyone loved waking up to ocean sounds and having direct beach access. The house easily accommodated our large group with plenty of space for everyone. Outdoor shower was convenient after beach days. Host was responsive and helped with restaurant reservations. Wonderful memories made here!',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2024-11-05').toISOString(),
        },
        {
            propertyId: 4,
            userId: 10,
            rating: 4.6,
            comment: 'Charming countryside cottage with so much character and warmth. The fireplace was perfect for cozy evenings with a good book. Garden was lovely for morning walks. Kitchen was well-equipped and we enjoyed cooking local produce. Village nearby had everything we needed. Host left thoughtful welcome basket. Very peaceful and rejuvenating stay.',
            cleanliness: 5,
            accuracy: 4,
            checkIn: 5,
            communication: 5,
            location: 4,
            value: 5,
            createdAt: new Date('2024-11-18').toISOString(),
        },
        {
            propertyId: 5,
            userId: 12,
            rating: 4.7,
            comment: 'Wonderful lakeside retreat that provided the perfect escape from daily stress. The kayaks and paddleboards were a great touch. Fishing from the dock was relaxing and we caught several bass. Interior was comfortable and clean with a well-stocked kitchen. Loved the screened porch for bug-free evening relaxation. Great communication from host throughout.',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 4,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2024-12-02').toISOString(),
        },
        {
            propertyId: 6,
            userId: 14,
            rating: 4.8,
            comment: 'Gorgeous villa that exceeded our expectations in every way! The infinity pool overlooking the valley was absolutely stunning. Outdoor entertaining space was perfect for our anniversary celebration. Bedrooms were spacious with luxurious bedding. Kitchen had professional-grade appliances. Host went above and beyond to make our stay special. Worth every penny!',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2024-12-15').toISOString(),
        },
        {
            propertyId: 2,
            userId: 13,
            rating: 4.5,
            comment: 'Great downtown apartment with fantastic city views. The floor-to-ceiling windows flooded the space with natural light. Building amenities were excellent including the rooftop terrace. Located near great restaurants and shopping. Parking was convenient in the garage. Minor issue with AC but host resolved it quickly. Overall a comfortable and convenient stay.',
            cleanliness: 4,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2025-01-08').toISOString(),
        },
        {
            propertyId: 3,
            userId: 15,
            rating: 4.9,
            comment: 'Absolutely magical mountain getaway that we never wanted to leave! The cabin was beautifully rustic yet had all modern conveniences. Hot tub under the stars was heavenly after hiking. Wildlife viewing from the deck was an unexpected bonus. Host provided detailed hiking guides and local recommendations. Already planning our return visit. Perfect mountain escape!',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 5,
            createdAt: new Date('2025-01-22').toISOString(),
        },
        {
            propertyId: 1,
            userId: 1,
            rating: 4.7,
            comment: 'Second time staying at this beachfront gem and it was just as wonderful as the first! Love the open floor plan and how close we are to the water. Sunrises from the master bedroom are breathtaking. Having beach chairs and umbrellas provided was so convenient. Kitchen is well-stocked for cooking. Always feel at home here.',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 4,
            location: 5,
            value: 5,
            createdAt: new Date('2025-02-05').toISOString(),
        },
        {
            propertyId: 4,
            userId: 3,
            rating: 4.6,
            comment: 'Delightful country cottage perfect for a romantic weekend away. The attention to detail in the decor was impressive. Loved the clawfoot tub for relaxing soaks. Garden was pristine and peaceful for morning coffee. Local farmer\'s market nearby had amazing fresh produce. Host was friendly and gave great restaurant recommendations. Wonderful quiet retreat.',
            cleanliness: 5,
            accuracy: 4,
            checkIn: 5,
            communication: 5,
            location: 4,
            value: 5,
            createdAt: new Date('2025-02-18').toISOString(),
        },
        {
            propertyId: 5,
            userId: 5,
            rating: 4.8,
            comment: 'Perfect lakefront property for our family vacation! Kids had a blast swimming off the dock and fishing. The fire pit area was ideal for s\'mores and stargazing. Cabin was spacious enough for everyone with comfortable beds. Kitchen had everything we needed. Loved the peaceful surroundings and abundant wildlife. Creating memories we will treasure forever!',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2025-03-03').toISOString(),
        },
        {
            propertyId: 6,
            userId: 7,
            rating: 4.9,
            comment: 'Stunning luxury villa that made our vacation truly special! The outdoor living space with pool and kitchen was where we spent most of our time. Master suite was like a private retreat with spa bathroom. Every detail was thoughtfully designed. Location offered privacy yet was close to attractions. Host was attentive without being intrusive. Absolutely phenomenal property!',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 5,
            createdAt: new Date('2025-03-17').toISOString(),
        },
        {
            propertyId: 2,
            userId: 9,
            rating: 4.7,
            comment: 'Excellent city apartment with all the conveniences we needed. The modern kitchen was perfect for preparing meals. Loved having a washer and dryer in unit. Building location made getting around the city easy. Secure parking was a huge plus. WiFi was fast and reliable for remote work. Host provided detailed information about the area. Great urban home base.',
            cleanliness: 5,
            accuracy: 5,
            checkIn: 5,
            communication: 5,
            location: 5,
            value: 4,
            createdAt: new Date('2025-03-28').toISOString(),
        },
    ];

    await db.insert(reviews).values(sampleReviews);
    
    console.log('✅ Reviews seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});