import { db } from '@/db';
import { users } from '@/db/schema';

async function main() {
    const sampleUsers = [
        {
            email: 'sarah.johnson@gmail.com',
            name: 'Sarah Johnson',
            avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330/photo-id?w=150&q=80',
            phone: '+1-555-234-5678',
            bio: 'Travel enthusiast who loves exploring new cities and trying local cuisine. Always looking for unique stays with character.',
            userType: 'guest',
            joinedAt: new Date('2022-03-15').toISOString(),
            isVerified: true,
        },
        {
            email: 'michael.host@outlook.com',
            name: 'Michael Chen',
            avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d/photo-id?w=150&q=80',
            phone: '+1-555-876-3421',
            bio: 'Passionate host with 5 years of experience. I believe in creating welcoming spaces where guests feel at home.',
            userType: 'host',
            joinedAt: new Date('2022-06-20').toISOString(),
            isVerified: true,
        },
        {
            email: 'emily.martinez@yahoo.com',
            name: 'Emily Martinez',
            avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80/photo-id?w=150&q=80',
            phone: '+1-555-432-9087',
            bio: 'Digital nomad who hosts properties in multiple cities while traveling the world. Love meeting people from different cultures.',
            userType: 'both',
            joinedAt: new Date('2022-08-10').toISOString(),
            isVerified: true,
        },
        {
            email: 'james.wilson@gmail.com',
            name: 'James Wilson',
            avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e/photo-id?w=150&q=80',
            phone: '+1-555-654-2109',
            bio: 'Adventure seeker and nature lover. Prefer mountain cabins and beachfront properties for weekend getaways.',
            userType: 'guest',
            joinedAt: new Date('2022-11-05').toISOString(),
            isVerified: true,
        },
        {
            email: 'lisa.anderson@hotmail.com',
            name: 'Lisa Anderson',
            avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2/photo-id?w=150&q=80',
            phone: '+1-555-987-4563',
            bio: 'Real estate investor and host dedicated to providing five-star experiences. Attention to detail is my priority.',
            userType: 'host',
            joinedAt: new Date('2023-01-18').toISOString(),
            isVerified: true,
        },
        {
            email: 'david.brown@gmail.com',
            name: 'David Brown',
            avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e/photo-id?w=150&q=80',
            phone: '+1-555-321-8765',
            bio: 'Family-oriented traveler who enjoys booking spacious homes for vacation. Also rent out my lake house during summer.',
            userType: 'both',
            joinedAt: new Date('2023-02-28').toISOString(),
            isVerified: true,
        },
        {
            email: 'amanda.taylor@icloud.com',
            name: 'Amanda Taylor',
            avatar: 'https://images.unsplash.com/photo-1487412720507-e7ab37603c6f/photo-id?w=150&q=80',
            phone: '+1-555-765-2341',
            bio: 'Wine enthusiast who loves staying at vineyard properties. Always booking my next weekend escape.',
            userType: 'guest',
            joinedAt: new Date('2023-04-12').toISOString(),
            isVerified: false,
        },
        {
            email: 'robert.host@gmail.com',
            name: 'Robert Garcia',
            avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d/photo-id?w=150&q=80',
            phone: '+1-555-234-8901',
            bio: 'Retired architect who converted historic properties into charming rentals. Love sharing stories about each buildings history.',
            userType: 'host',
            joinedAt: new Date('2023-05-30').toISOString(),
            isVerified: true,
        },
        {
            email: 'jennifer.lee@yahoo.com',
            name: 'Jennifer Lee',
            avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb/photo-id?w=150&q=80',
            phone: '+1-555-890-1234',
            bio: 'Yoga instructor who hosts wellness retreats at my mountain property. Also travel frequently to teach workshops.',
            userType: 'both',
            joinedAt: new Date('2023-07-08').toISOString(),
            isVerified: true,
        },
        {
            email: 'william.davis@outlook.com',
            name: 'William Davis',
            avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556/photo-id?w=150&q=80',
            phone: '+1-555-456-7890',
            bio: 'Business traveler seeking comfortable stays in downtown areas. Value reliable wifi and quiet workspaces.',
            userType: 'guest',
            joinedAt: new Date('2023-08-22').toISOString(),
            isVerified: true,
        },
        {
            email: 'sophia.superhost@gmail.com',
            name: 'Sophia Rodriguez',
            avatar: 'https://images.unsplash.com/photo-1489424731084-a5d8b219a5bb/photo-id?w=150&q=80',
            phone: '+1-555-678-9012',
            bio: 'Superhost with properties in three cities. Committed to sustainable hosting and creating memorable experiences for every guest.',
            userType: 'host',
            joinedAt: new Date('2023-09-15').toISOString(),
            isVerified: true,
        },
        {
            email: 'daniel.thompson@icloud.com',
            name: 'Daniel Thompson',
            avatar: 'https://images.unsplash.com/photo-1519345182560-3f2917c472ef/photo-id?w=150&q=80',
            phone: '+1-555-901-2345',
            bio: 'Photographer who travels for work and hosts my studio loft when away. Love meeting creative guests and sharing local art scenes.',
            userType: 'both',
            joinedAt: new Date('2023-10-20').toISOString(),
            isVerified: true,
        },
        {
            email: 'olivia.green@hotmail.com',
            name: 'Olivia Green',
            avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9/photo-id?w=150&q=80',
            phone: '+1-555-123-6789',
            bio: 'Festival and concert goer always looking for cool places near event venues. Love connecting with other music fans.',
            userType: 'guest',
            joinedAt: new Date('2023-11-30').toISOString(),
            isVerified: false,
        },
        {
            email: 'thomas.host@gmail.com',
            name: 'Thomas White',
            avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce/photo-id?w=150&q=80',
            phone: '+1-555-345-6780',
            bio: 'Chef and host who offers cooking classes at my countryside villa. Passionate about farm-to-table experiences and hospitality.',
            userType: 'host',
            joinedAt: new Date('2024-01-10').toISOString(),
            isVerified: true,
        },
        {
            email: 'mia.traveler@yahoo.com',
            name: 'Mia Patel',
            avatar: 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce/photo-id?w=150&q=80',
            phone: '+1-555-567-8901',
            bio: 'Solo traveler and remote worker who rents cozy apartments worldwide. Also host my condo when traveling for extended periods.',
            userType: 'both',
            joinedAt: new Date('2024-02-14').toISOString(),
            isVerified: true,
        },
    ];

    await db.insert(users).values(sampleUsers);
    
    console.log('✅ Users seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});